### ISSUE TITLE
source repository contains binaries

### ISSUE THREAD

**Issue by adrelanos** [eyedeekay/firefox.profile.i2p#15]
* the extensions https://github.com/eyedeekay/firefox.profile.i2p/tree/master/firefox.profile.i2p/extensions
* https://github.com/eyedeekay/firefox.profile.i2p/blob/master/firefox.profile.i2p/storage-sync.sqlite
* possibly also https://github.com/eyedeekay/firefox.profile.i2p/blob/master/firefox.profile.i2p/search.json.mozlz4

**Comment by eyedeekay** [comment]
They are now removed. Found the script for extracting mozlz4 files too. Sorry for the long delay.
