### ISSUE TITLE
Windows update profile in-place

### ISSUE THREAD

**Issue by eyedeekay** [eyedeekay/firefox.profile.i2p#4]
I want the windows installer to be able to download an updated profile if a new version has become available, and unpack it to the correct directory. Just do it at the top of the static bat's for Windows zip, and I'm sure something as scriptable as NSIS can handle this.

**Comment by zlatinb** [comment]
That would be really cool, then we don't need to ship the full profile with the I2P distribution.  NSIS has at least two plugins for downloading files.

**Comment by eyedeekay** [comment]
In general I'd like to have the same features across all platforms, and the Linux script can already do this, so I'm going to try and do it tonight when I do the menus for the Windows installer.

**Comment by eyedeekay** [comment]
Tentatively done. If and only if an existing profile is detected, It moves the old profile to a backup folder, downloads an update profile zip and unpacks it. It doesn't check the signature yet.
