### ISSUE TITLE
.lnk shortcuts need quotes around the strings

### ISSUE THREAD

**Issue by zlatinb** [eyedeekay/firefox.profile.i2p#6]
Hi, the desktop & start menu shortcuts now point to

`
C:\Windows\System32\cmd.exe \c C:\Program Files (x86)\I2P\I2PBrowser-Launcher\i2pbrowser.bat
`

and as a result all they do is launch a command prompt.  In order for them to work the path of the .bat file should be in quotation marks.

**Comment by eyedeekay** [comment]
I think I've fixed it, but don't have the ability to test it until I get home. I put the new exe up the releases if you want to try it now..

**Comment by zlatinb** [comment]
Just tested it - almost there.  What's left is to change the "\c" to "/c" and it will work.

**Comment by eyedeekay** [comment]
Awesome
