### ISSUE TITLE
NOTFOUND even though I have 32-bit Firefox

### ISSUE THREAD

**Issue by zlatinb** [eyedeekay/firefox.profile.i2p#7]
I am running 64-bit Win10 VM with exactly 2GB RAM.  The Firefox stub installer chose to install 32-bit Firefox in "C:\Program Files (x86)\Mozilla Firefox\firefox.exe"

However, running the latest release installer generates a .bat file with NOTFOUND:

@echo off
start "" "NOTFOUND" -no-remote -profile "C:\Users\zab\AppData\Local\I2PBrowser-Launchet\firefox.profile.i2p"
pause

**Comment by eyedeekay** [comment]
I think I've addressed this with the latest version, which I put on the release channel. Same story test-wise, unfortunately. I've got to wait to get home to do it myself.

**Comment by zlatinb** [comment]
The latest installer displays a selection dialog asking where is my installation of Firefox, and when I put in the right location it generates a working .bat file 👍 

I think the reason it is not auto-detecting is that you have set the minimum memory to
`!define RAM_NEEDED_FOR_64BIT 1887436800`
whereas in the Firefox stub installer that value is (line 195)
`!define RAM_NEEDED_FOR_64BIT 0x80000000`

**Comment by eyedeekay** [comment]
> The latest installer displays a selection dialog asking where is my installation of Firefox, and when I put in the right location it generates a working .bat file

Sweet, that's about how I expected it to work. I can figure out how to automatically set it to the architecture default when I get home.

> I think the reason it is not auto-detecting is that you have set the minimum memory to
> !define RAM_NEEDED_FOR_64BIT 1887436800
> whereas in the Firefox stub installer that value is (line 195)
> !define RAM_NEEDED_FOR_64BIT 0x80000000

That is weird as hell. I totally got that number by searching the file for that exact variable. I wonder how I did that.
